### ISSUE TITLE
Provide access to analysis summary level information

### ISSUE THREAD

**Issue by realtonyyoung** [sisudata/pysisu#6]
When loading analysis information through pysisu, it's critical to be able to access two main pieces of information:

1. The name of the analysis: for example Tony Young Group Comparison in the attached screenshot
2. The group or time comparison summary information: for example the SilverMembers vs. GoldMembers section complete with metric name, metric value, overall impact change, min, max, median, average, sum and rows

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6655045/178320031-642387dd-c560-4c6f-b2bf-cf4941e09a48.png">

**Comment by chitalian** [comment]
Closing since this is an API request and not a pysisu requst
