### ISSUE TITLE
Impact field missing from pysisu get_results

### ISSUE THREAD

**Issue by realtonyyoung** [sisudata/pysisu#7]
Each fact of a Sisu analysis returns an `Impact on Change in Average` field. This field is missing from the table returned by pysisu get_results and is critical for external presentation of the fact

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6655045/178320758-17eb31ac-8d86-4e85-8f52-99a3108bb5c4.png">

**Comment by chitalian** [comment]
This is a limitation of the API and not pysisu
